### ISSUE TITLE
'update_tool': uncaught JSONDecodeError exception

### ISSUE THREAD

**Issue by pjbriggs** [pjbriggs/nebulizer#86]
Attempting to update `iuc/trinity_analyze_diff_expr` using Nebulizer 0.6.0 gets an uncaught `JSONDecodeError` exception which crashes Nebulizer (the operation still completes in Galaxy).

The problem occurs when the connection with the initial tool install attempt is broken, presumably all that is required is an extension to the exception handling in the `install_tool` function:

    ...
    trinity_analyze_diff_expr: requesting installation
    WARNING:nebulizer.tools:Got error from Galaxy API on attempted install (ignored)
    WARNING:nebulizer.tools:Status code: 504
    Traceback (most recent call last):
      File "/home/pjb/virtual-envs/nebulizer/bin/nebulizer", line 8, in <module>
        sys.exit(nebulizer())
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.6/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.6/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.6/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
        return ctx.invoke(f, obj, *args[1:], **kwargs)
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.    6/site-packages/nebulizer/cli.py", line 887, in update_tool
        (install_resolver_dependencies== 'yes')))
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.6/site-packages/nebulizer/tools.py", line 1322, in update_tool
        no_wait=no_wait)
      File "/home/pjb/virtual-envs/nebulizer/lib/python3.6/site-packages/nebulizer/tools.py", line 1189, in install_tool
        json.loads(connection_error.body)["err_msg"])
      File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by pjbriggs** [comment]
NB the `JSONDecodeError` only appears in the `json` module for Python3 - in Python 2.7 it looks like you get a `ValueError` exception instead: https://stackoverflow.com/a/35214768

**Comment by mvdbeek** [comment]
Hey @pjbriggs .... the 504 is a timeout from your proxy. The problem is with repository installations in Galaxy taking too much time before returning a response from Galaxy. We've worked around this in ephemeris here: https://github.com/galaxyproject/ephemeris/blob/master/src/ephemeris/shed_tools.py#L396. When this happens we instead list all installed repositories and try to figure out which repository is currently non-terminal (https://github.com/galaxyproject/ephemeris/blob/master/src/ephemeris/shed_tools.py#L60), and then we wait on that repository here: https://github.com/galaxyproject/ephemeris/blob/master/src/ephemeris/shed_tools.py#L442

The handling on Galaxy's side is really unfortunate, but I think we're getting closer to being able to just return an encoded repository id as soon as it exists and continue installing in the background, so that the client (nebulizer/ephemeris/the galaxy user interface) can just track updates to a specific repository id.

**Comment by pjbriggs** [comment]
Hello @mvdbeek thanks for the additional information.

The problem here isn't actually the timeout, so much as that I'm not doing a very good job of reporting it before dropping into a "monitoring" mode! (I haven't looked at the Ephemeris code but the monitoring sounds superficially quite similar.)

Right now I'm wondering if it might be better just to silently ignore these exceptions before going into monitoring the install (so as not to alarm the user unnecessarily).

Longer term having the repository installation work in background on the Galaxy side would be great. But I think these issues are wrinkles - the API still feels like magic to me, and seems to be improving all the time.

**Comment by pjbriggs** [comment]
Fixed by PR #88.
